### ISSUE TITLE
4k下载下来没有声音

### ISSUE THREAD

**Issue by obrua** [kengwang/BiliDuang#13]

**Comment by kengwang** [comment]
请使用 开发版 的mp4box版，ffmpeg会抽风。因为时间原因没来得及更新release，烦请自行编译下

https://github.com/kengwang/BiliDuang/commit/ded51f4f984b1bf157b1b3ab36df34400f75c1c2

**Comment by kengwang** [comment]
这周末回家会把mp4box版本发成release，现在暂时没时间

**Comment by kengwang** [comment]
mp4box不支持合并flv,我看干脆还是flv用ffmpeg,mp4用mp4box
该Issue重开,今天有时间的话就更

**Comment by kengwang** [comment]
https://www.cnblogs.com/xiaotie/p/3441030.html
flv有望原生实现 (欢呼)
之后会加个新的视频链接接口,但是下载下来是mp4. 可以供你们选择

**Comment by kengwang** [comment]
即将发Release,稍等,我打个包

**Comment by kengwang** [comment]
https://github.com/kengwang/BiliDuang/releases/tag/v2.1.2-fix
已打包关Issue
