### ISSUE TITLE
null

### ISSUE THREAD

**Issue by hax0r31337** [kengwang/BiliDuang#14]

**Comment by kengwang** [comment]
我的天，还真有人用Linux！初步判断应该是ssl出错了。因为我也只是在Deepin上稍微跑了一下，把某些崩溃的地方改了改，没想到还是出问题了

**Comment by kengwang** [comment]
下个版本可能会修复，不过要等一段时间了…

**Comment by kengwang** [comment]
字体用的微软雅黑，deepin应该默认有点

**Comment by liulihaocai** [comment]
哦谢啦，我电脑垃圾，所以用linux会省点空间，少点占用，而且windows下的nodejs环境他不会自动清理垃圾，敲会代码，测试一会，电脑RAM就满了。。。
