### ISSUE TITLE
反馈一个BUG

### ISSUE THREAD

**Issue by zerokos** [kengwang/BiliDuang#27]
下载番剧例如 BV18s411c74T 时，如果用的api源是 **bilibili新版网页端**
下的每一集都是第一集，内容一摸一样，坐等开发者修复

**Comment by kengwang** [comment]
感谢反馈

**Comment by kengwang** [comment]
可能已经Fixed: https://github.com/kengwang/BiliDuang/commit/cc22bc39094675514ddf19b76339f9b7fbda9107

**Comment by zerokos** [comment]
> 可能已经Fixed: [cc22bc3](https://github.com/kengwang/BiliDuang/commit/cc22bc39094675514ddf19b76339f9b7fbda9107)

我测试了下最新版2.1.6· 还是用家庭教师reborn那个番剧， bilibili新版网页端api 解析出来的还是不对，都还是第一集

**Comment by kengwang** [comment]
新版Commit修复,等下我改Release

**Comment by kengwang** [comment]
https://github.com/kengwang/BiliDuang/releases/download/2.1.6/2.1.6.Arks-v1.zip

**Comment by zerokos** [comment]
> https://github.com/kengwang/BiliDuang/releases/download/2.1.6/2.1.6.Arks-v1.zip

经测试该版本依然存在BUG，无论是单独下载还是批量下载，都是第一集。

大大可以试试，每一集下载下来文件大小一模一样

测试番剧：BV18s411c74T
