### ISSUE TITLE
BUG未修复

### ISSUE THREAD

**Issue by zerokos** [kengwang/BiliDuang#29]
https://github.com/kengwang/BiliDuang/releases/download/2.1.6/2.1.6.Arks-v1.zip

经测试该版本依然存在BUG，无论是单独下载还是批量下载，无论清晰度选哪个，都是第一集。

大大可以试试，每一集下载下来文件大小一模一样

测试番剧：BV18s411c74T

**Comment by zerokos** [comment]
对了，忘了说，还是用的 **新版网页端** api

**Comment by kengwang** [comment]
emm,是用的BV进的吗?

**Comment by zerokos** [comment]
> emm,是用的BV进的吗?

是的
BV18s411c74T 和 ss1376 都试过，所有下载的还是第一集

**Comment by kengwang** [comment]
换了个方法来获取新的API,还在测试

**Comment by kengwang** [comment]
Fixed
see: https://github.com/kengwang/BiliDuang/releases/download/2.1.6/2.1.6.Arks.-.v2.zip
