### ISSUE TITLE
看里面

### ISSUE THREAD

**Issue by wenjvQAQ** [kengwang/BiliDuang#30]
`` Windows下如何编译 ``
###### 我不会
[`` 能回答直接说 ``](https://github.com/kengwang/BiliDuang/issues)
# windows10来的

**Comment by wenjvQAQ** [comment]
_我不会_

**Comment by kengwang** [comment]
Hi，你好。本项目是使用的Visual Studio 2019进行编译的，你可以前往 https://visualstudio.microsoft.com/zh-hans/vs/ 进行下载，在安装时，请注意勾选 C# 桌面开发， .NET 开发等相关选项。在安装好后下载项目源文件，打开其中的sln文件即可打开本项目
