### ISSUE TITLE
数量1000的视频遇到的问题和其它一些小问题。

### ISSUE THREAD

**Issue by 101101000** [kengwang/BiliDuang#34]
1.数量1000的视频解析出视频后，选择“选中全部”软件停止工作只能关闭程序。
2.数量1000的视频解析出视频后，不选择“选中全部”手动打勾选择视频，下拉到底后只能选择628个文件，后面的378个文件无法看到也不能选择。
3.有些文件无法合成mp4视频，是包含mp4 mp3的文件夹。
4.有一个视频集里，某些个别的文件选择下载，软件会停止工作，跳过这个视频就可以正常工作。

**Comment by 101101000** [comment]
5.个别的视频集遇到过下载10个视频后，软件停止工作。重新启动后，同意继续下载，下载10个视频后继续停止工作。

**Comment by kengwang** [comment]
感谢反馈，数量过大确实有点问题。而且我的错误处理也没有完善好。寒假再更了，马上期末考了

**Comment by kengwang** [comment]
选中全部崩溃是MaterialSkin背锅,他的animationtimer炸掉了,我尝试暴力修复,加个try catch
