### ISSUE TITLE
使用 BiliPlusAPI 获取2021年01月新番下载链接时报错崩溃。

### ISSUE THREAD

**Issue by ghost** [kengwang/BiliDuang#36]
> 有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 BiliDuang.DownloadObject.GetDownloadUrls()
   在 BiliDuang.DownloadObject.LinkStart()
   在 BiliDuang.DownloadQueue.StartAll(Boolean isauto)
   在 BiliDuang.UI.Download.DownloadList.RefreshUI()
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4220.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BiliDuang
    程序集版本:2.1.1.0
    Win32 版本:2.1.1.0
    基本代码:file:///D:/Users/Downloads/Compressed/2.1.6.Arks.-.v2/BiliDuang.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MaterialSkin
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Users/Downloads/Compressed/2.1.6.Arks.-.v2/MaterialSkin.DLL
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.3.23909
    基本代码:file:///D:/Users/Downloads/Compressed/2.1.6.Arks.-.v2/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4220.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by ghost** [comment]
经测试使用其它API虽然无法获取新港澳台的下载链接，但是程序不会崩溃。
测试番剧链接：https://www.bilibili.com/video/av458625237

请问这是由于我个人系统，还是 BiliPlusAPI 停用或港澳台策略变化的原因？
我该如何操作（有无解决办法）以解决这个问题呢？

>https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

请问后期有无可能添加功能，仿照Bili漫游那样自定义服务器接口返回解析的链接？

**Comment by MC-dusk** [comment]
首先Biliplus已经被B站屏蔽了，出问题的可能性很大。
其次这个av号链接我打不开，也没有跳转，能否提供番剧的ep号？

---

复议：

> 仿照Bili漫游那样自定义服务器接口返回解析的链接

**Comment by ghost** [comment]
@MC-dusk 

> https://acgsecrets.hk/bangumi/202101/

在这里你可以获取所有 1月 Bilibili 港澳台的 MD 链接

ps.如果不挂梯子访问港澳台番剧详情页会自动跳转404

**Comment by MC-dusk** [comment]
我目前测试下载外区的番剧都不行

**Comment by MC-dusk** [comment]
我目前测试下载外区的番剧都不行

**Comment by kengwang** [comment]
感谢反馈，目前的新版本（commit版本）支持 BiliRoaming 的公共解析服务器，因为还未测试泰国API完全，所以未发Release。
方法：
选择 第三方解析 填入公共解析服务器地址

**Comment by kengwang** [comment]
这周回去先发个Pre-Release吧，寒假再发Release

**Comment by kengwang** [comment]
> 仿照Bili漫游那样自定义服务器接口返回解析的链接

新版Commit已经支持自定义解析服务器地址,今天在Github发个Pre-release,Gitee就不发了不然会被推送更新

**Comment by ghost** [comment]
崩溃问题已解决（√）
目前港澳台又转回 “哔哩哔哩番剧出差” 的账号进行投稿了，验证机制也回归最原始的只限 IP 不限平台，老 API 也能正常使用了。 
有时间测试一下海外番剧的下载运行情况。
