### ISSUE TITLE
提问咨询：如何通过番剧的 ep_id 获取其对应的 season_id ?

### ISSUE THREAD

**Issue by hui-shao** [kengwang/BiliDuang#39]
如题，找了半天了，是不是有什么api接口？
看到作者你好像有这方面的研究，方便的话麻烦解答下哈

**Comment by kengwang** [comment]
我是直接硬取的,有点粗暴的做法,因为我也没找到合适的API

> string callback = Other.GetHtml("https://www.bilibili.com/bangumi/play/ep" + epid);
> ssid = Other.TextGetCenter("content=\"https://www.bilibili.com/bangumi/play/ss", "/\">", callback);

**Comment by hui-shao** [comment]
好的，感谢解答。
我本来是想把某“泰国番剧”加入追番列表，但是国内番剧页面打不开（会提示不存在），抓包分析点击追番按钮后的通信，发现season_id是必不可少的一个参数......
