### ISSUE TITLE
批量下载显示分片0下载错误，未能找到路径

### ISSUE THREAD

**Issue by gwL955** [kengwang/BiliDuang#40]
## BUG 反馈

**何处触发：

在搜索框键入UP主链接，并选择稿件，批量下载，以及选择收藏夹批量下载，下载管理均显示显示分片0下载错误，未能找到路径

**配置与环境：

- Bilibili 链接：https://space.bilibili.com/1724598/
- 正在使用的 API:https://api.bilibili.com
- BiliDuang 版本：2.1.7
- 系统版本：win10 1909专业版
- .NET 版本：(如不知道可不填)

**截图（若有）**
![截图](https://user-images.githubusercontent.com/78864083/107529045-7213ec80-6bf5-11eb-95c9-c6d82d5bb1e9.png)

**报错信息**
分片0下载错误：未能找到路径

**Comment by kengwang** [comment]
您的错误报告已经收到,正在排查

**Comment by kengwang** [comment]
emm,好像是下载的时候没有自动创建下载到的文件夹

**Comment by kengwang** [comment]
正在修复,还有几个BUG修复一起跟着发

**Comment by kengwang** [comment]
Fixed in 6388fd08756d22b3f83098c912958f7dd24c2964

**Comment by kengwang** [comment]
因为改动很小所以没有发Release: 发成附件放在这个Issue里面吧
[2.1.7 Staroshi - Fixed.zip](https://github.com/kengwang/BiliDuang/files/5959471/2.1.7.Staroshi.-.Fixed.zip)
