### ISSUE TITLE
独播动画无法下载

### ISSUE THREAD

**Issue by ashuai** [kengwang/BiliDuang#41]
## BUG 反馈

无法下载

**这个问题出在程序的哪一个具体功能？**
无法下载
只试了2个API源：bilibili TV和bilibili

**预期的行为：**
正常下载

**配置与环境：**

- Bilibili 链接：https://www.bilibili.com/bangumi/play/ep384211
- 正在使用的 API: bilibili TV和bilibili
- BiliDuang 版本：2.1.7-Staroshi-Fixed
- 系统版本：Win10 2004
- .NET 版本：4.8

**Comment by kengwang** [comment]
您好,已经收到了您的Issue,正在排查

**Comment by kengwang** [comment]
![图片](https://user-images.githubusercontent.com/30862240/108187877-e7c60e00-7149-11eb-9c78-2f7ab34b57a7.png)
我这边API: `Bilibili` 下载得了

**Comment by kengwang** [comment]
Bilibili TV不支持番剧无水印,因为番剧是上传到服务器前加的水印
