### ISSUE TITLE
解析服务器鉴权

### ISSUE THREAD

**Issue by AisukaYuki** [kengwang/BiliDuang#47]
源码引用的case5是我的解析服务器，加了鉴权的，强制添加链接参数area=XX鉴权，以及api漫游客户端鉴权。只适用于漫游插件和网页脚本。PS：大多解析服务器都采用了基本相同鉴权方式。

**Comment by kengwang** [comment]
感谢反馈，将在近期作出调整

**Comment by kengwang** [comment]
423bc7f 已经完成并重构解析算法
