### ISSUE TITLE
现在是选4K，默认下载最高清嘛？

### ISSUE THREAD

**Issue by dmhai** [kengwang/BiliDuang#5]
现在的下载是优先最高清嘛？要不，咱探测一下清晰度列表，下拉框只显示支持的清晰度？

**Comment by kengwang** [comment]
假如清晰度没达到那么高会自动往下调整的。现在已经支持4K视频下载了

**Comment by kengwang** [comment]
> 现在的下载是优先最高清嘛？要不，咱探测一下清晰度列表，下拉框只显示支持的清晰度？

对不起，我现在才看懂意思。先就探测一遍的话会很卡

**Comment by dmhai** [comment]
好吧，没想到这么麻烦，我还以为会在解析过程中就能拿到清晰度。
就像我解析tx云课堂一样，在解析课程信息拿视频m3u8的过程中，就有不同清晰度的数组结果。
那么麻烦，那就不做了。
