### ISSUE TITLE
支持使用cookies登录以便支持泰区

### ISSUE THREAD

**Issue by zhongfly** [kengwang/BiliDuang#50]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**
可以填入账号登录后的cookies或access_key来在此工具中登录

**这个想法实现后有什么帮助？**
方便登录泰区账号而不需要在工具中用网页登录

**补充信息：**
也许再增加一个账号切换系统会更方便

**Comment by kengwang** [comment]
右键 BiliDuang 的 登录按钮,你会看到填 Cookie 的地方

**Comment by kengwang** [comment]
另: 泰区暂未进行适配
