### ISSUE TITLE
错误	CS0234	命名空间“MaterialSkin.Controls”中不存在类型或命名空间名“MaterialComboBox”

### ISSUE THREAD

**Issue by dlxj** [kengwang/BiliDuang#57]
错误	CS0234	命名空间“MaterialSkin.Controls”中不存在类型或命名空间名“MaterialComboBox”(是否缺少程序集引用?)	BiliDuang	D:\csharp\BiliDuang\BiliDuang\MainForm.Designer.cs	885	活动

环境：

Win10 + VS2019

已安装 MaterialSkin 0.2.1

**Comment by kengwang** [comment]
旧版已废,新版在写, 见 wpf 分支
