### ISSUE TITLE
这么卡，主线程蹦迪？

### ISSUE THREAD

**Issue by PlexPt** [kengwang/BiliDuang#7]

**Comment by kengwang** [comment]
我视频图片加载放在主线程的，假如嫌卡开低缓存模式

**Comment by PlexPt** [comment]
那就放到子线程啊

**Comment by kengwang** [comment]
低缓存不会主动缓存图片，这样的话加载速度快很多！要不之后版本默认开启？

**Comment by kengwang** [comment]
好吧，大佬说得对，之后放到子线程吧……主线程加载确实别扭……

**Comment by kengwang** [comment]
这周就修，有思路了。

**Comment by kengwang** [comment]
修复了,修复了,这样可以了吧

**Comment by kengwang** [comment]
假如加载的很多还是建议手动开启低缓存模式，开子线程不断开也很卡

**Comment by kengwang** [comment]
我发现我理解错意思了,马上就改
https://github.com/kengwang/BiliDuang/projects/3#card-46664067
