### ISSUE TITLE
如何在 Linux 系统下运行

### ISSUE THREAD

**Issue by kengwang** [kengwang/BiliDuang#9]
有某些大佬使用的是 Linux 操作系统,本软件针对于 Linux 有 UI 优化
在运行之前你需要安装 `Mono` 来运行此程序
> 请注意: 此程序用 `Wine` 打开会只是您用 `Mono` 打开

你可以跟随 [Mono官网](https://www.mono-project.com/download/stable) 的教程来安装
如果你是 Ubuntu 的用户，你也可以尝试使用软件包管理器安装 `mono-complete`

当你安装好 `Mono` 后,您还需要安装 `mp4box` ,这个可以进行4K视频的合并.
你也可以跟随 [GPAC官网](https://gpac.wp.imt.fr/downloads/) 来进行安装

之后你就可以执行
```shell
mono BiliDuang.exe
```
来打开 BiliDuang 了,你会惊奇的发现打开了主窗口,所有功能几乎一模一样.

**Comment by kengwang** [comment]
Linux 下的登录准备采用纯二维码的方式，我会单独写一套。
Windows还是老样子，因为功能够了
先关下Issue，之后再开

**Comment by kengwang** [comment]
#14 的问题正在追踪中

**Comment by liyishuai** [comment]
## 苹果机运行大失败
- 操作系统：macOS 12.2.1 Monterey
- BiliDuang版本：2.1.8

### 一周目
- 执行命令：
    ```shell
    mono BiliDuang.exe
    ```
- 标准输出：[monologs.txt](https://github.com/kengwang/BiliDuang/files/8312071/monologs.txt)
  > System.NotSupportedException: Specified method is not supported.
- 错误输出：[monoerr.txt](https://github.com/kengwang/BiliDuang/files/8312074/monoerr.txt)
  > Unhandled Exception:
System.DllNotFoundException: user32.dll assembly:<unknown assembly> type:<unknown type> member:(null)
- 相关问题：https://stackoverflow.com/questions/1314645/equivalent-of-user32-dll-on-os-x

### 二周目
- 执行命令：
    ```shell
    mono32 BiliDuang.ext
    ```
- 响应：
  > zsh: bad CPU type in executable: mono32
- 相关问题：mono/mono#6701
